### ISSUE TITLE
Angular 'Get(id: any)' does not work

### ISSUE THREAD

**Issue by patrickmichalina** [gallayl/FuryTech.OdataTypescriptServiceGenerator#3]
Works in angular2-odata. This code is different though. Also, why is everything a promise instead of Observable?

Problem code:
```typescript
    private async evaluateGetOperation(queryString: string): Promise<T> {
        return this.http.get(this.entitySetUrl + queryString, {
            withCredentials: true,
        }).map(a => {
            return a.json() as T;
        }).toPromise();
    }

    public Get(id: any): ODataGetOperation<T> {
        let idSegment = this.getEntityUriSegment(id);
        return new ODataGetOperation<T>(idSegment, this.evaluateGetOperation);
    };
```

**Comment by gallayl** [comment]
Moved the evaluateGetOperation() to an inline declaration, but haven't tested in Angular2 (please reopen if you're still in trouble with it)
The reason behind the Promist<T>'s is that you can use the async-await pattern, (and the async pipe aswell) but is make sense to create an another template to use observeables for Angular.
